name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: elasticsearch
        ports:
        - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: curl http://localhost:${{ job.services.elasticsearch.ports[9200] }}/_cluster/health
